In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'..\dataset\WELFake_Dataset.csv')

In [4]:
df.shape

(72134, 4)

In [5]:
df.columns.tolist()

['Unnamed: 0', 'title', 'text', 'label']

In [6]:
df

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [7]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [8]:
df

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

To drop the rows where there is no article text.

In [9]:
df.dropna(subset = ['text'], inplace = True)

To fill the title with empty string where no article title, because article text is still present.

In [10]:
df['title'] = df['title'].fillna('')

In [11]:
df[['title','text','label']].isna().sum()

title    0
text     0
label    0
dtype: int64

So no more remaining null values in the dataset now.

In [12]:
df.shape

(72095, 3)

We have to create a column content which will have both article title and text combined becuase we need to have the content in a single place to where the model will access.

In [13]:
df['Content'] = df['title'] + ' ' + df['text']

In [14]:
df['Content'].iloc[0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO] No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News'

In [15]:
len(df['Content'].iloc[0])

5180

# Text Cleaning

In [16]:
import re

In [17]:
def clean(text):
    text = text.lower()
    text = re.sub(r'http\S+ | www\S+', '', text)
    text = re.sub(r'@\w+ | #\w+', '', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = ' '.join([i for i in text.split() if len(i) > 1])
    text = re.sub(r'\s+', ' ', text)
    return text

In [18]:
sample = df['Content'].iloc[0]

Before cleaning:

In [19]:
sample[:300]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO] No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cop'

After Cleaning:

In [20]:
clean(sample)[:300]

'law enforcement on high alert following threats against cops and whites on by and terrorists no comment is expected from barack obama members of the or and movements called for the lynching and hanging of white people and cops they encouraged others on radio show tuesday night to turn the tide and k'

In [21]:
df['Content']

0        LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1           Did they post their votes for Hillary already?
2        UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3        Bobby Jindal, raised Hindu, uses story of Chri...
4        SATAN 2: Russia unvelis an image of its terrif...
                               ...
72129    Russians steal research on Trump in hack of U....
72130     WATCH: Giuliani Demands That Democrats Apolog...
72131    Migrants Refuse To Leave Train At Refugee Camp...
72132    Trump tussle gives unpopular Mexican leader mu...
72133    Goldman Sachs Endorses Hillary Clinton For Pre...
Name: Content, Length: 72095, dtype: object

In [22]:
df['Cleaned'] = df['Content'].apply(clean)

In [23]:
df.shape

(72095, 5)

In [24]:
df['Cleaned']

0        law enforcement on high alert following threat...
1            did they post their votes for hillary already
2        unbelievable obamas attorney general says most...
3        bobby jindal raised hindu uses story of christ...
4        satan russia unvelis an image of its terrifyin...
                               ...
72129    russians steal research on trump in hack of us...
72130    watch giuliani demands that democrats apologiz...
72131    migrants refuse to leave train at refugee camp...
72132    trump tussle gives unpopular mexican leader mu...
72133    goldman sachs endorses hillary clinton for pre...
Name: Cleaned, Length: 72095, dtype: object

In [25]:
s = df['Cleaned'].iloc[0][:].split()

In [26]:
print([i for i in s if len(i) == 1])

[]

In [27]:
import nltk

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vansh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
from nltk.corpus import stopwords

In [30]:
stop_words = set(stopwords.words('english'))

In [31]:
len(stop_words)

198

In [32]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [33]:
sample_words = df['Cleaned'].iloc[0].split()
sample_words

['law',
 'enforcement',
 'on',
 'high',
 'alert',
 'following',
 'threats',
 'against',
 'cops',
 'and',
 'whites',
 'on',
 'by',
 'and',
 'terrorists',
 'no',
 'comment',
 'is',
 'expected',
 'from',
 'barack',
 'obama',
 'members',
 'of',
 'the',
 'or',
 'and',
 'movements',
 'called',
 'for',
 'the',
 'lynching',
 'and',
 'hanging',
 'of',
 'white',
 'people',
 'and',
 'cops',
 'they',
 'encouraged',
 'others',
 'on',
 'radio',
 'show',
 'tuesday',
 'night',
 'to',
 'turn',
 'the',
 'tide',
 'and',
 'kill',
 'white',
 'people',
 'and',
 'cops',
 'to',
 'send',
 'message',
 'about',
 'the',
 'killing',
 'of',
 'black',
 'people',
 'in',
 'americaone',
 'of',
 'the',
 'fyoflag',
 'organizers',
 'is',
 'called',
 'sunshine',
 'she',
 'has',
 'radio',
 'blog',
 'show',
 'hosted',
 'from',
 'texas',
 'called',
 'sunshine',
 'fing',
 'opinion',
 'radio',
 'show',
 'snapshot',
 'of',
 'her',
 'twitter',
 'page',
 'at',
 'pm',
 'shows',
 'that',
 'she',
 'was',
 'urging',
 'supporters',
 'to',
 'call',
 'now',
 'tonight',
 'we',
 'continue',
 'to',
 'dismantle',
 'the',
 'illusion',
 'of',
 'white',
 'below',
 'is',
 'snapshot',
 'twitter',
 'radio',
 'call',
 'invite',
 'radio',
 'show',
 'aired',
 'at',
 'pm',
 'eastern',
 'standard',
 'timeduring',
 'the',
 'show',
 'callers',
 'clearly',
 'call',
 'for',
 'lynching',
 'and',
 'killing',
 'of',
 'white',
 'peoplea',
 'minute',
 'clip',
 'from',
 'the',
 'radio',
 'show',
 'can',
 'be',
 'heard',
 'here',
 'it',
 'was',
 'provided',
 'to',
 'breitbart',
 'texas',
 'by',
 'someone',
 'who',
 'would',
 'like',
 'to',
 'be',
 'referred',
 'to',
 'as',
 'hannibal',
 'he',
 'has',
 'already',
 'received',
 'death',
 'threats',
 'as',
 'result',
 'of',
 'interrupting',
 'conference',
 'callsan',
 'unidentified',
 'black',
 'man',
 'said',
 'when',
 'those',
 'mother',
 'fkers',
 'are',
 'by',
 'themselves',
 'that',
 'when',
 'when',
 'we',
 'should',
 'start',
 'fing',
 'them',
 'up',
 'like',
 'they',
 'do',
 'us',
 'when',
 'bunch',
 'of',
 'them',
 'niers',
 'takin',
 'one',
 'of',
 'us',
 'out',
 'that',
 'how',
 'we',
 'should',
 'roll',
 'up',
 'he',
 'said',
 'cause',
 'we',
 'already',
 'roll',
 'up',
 'in',
 'gangs',
 'anyway',
 'there',
 'should',
 'be',
 'six',
 'or',
 'seven',
 'black',
 'mother',
 'fckers',
 'see',
 'that',
 'white',
 'person',
 'and',
 'then',
 'lynch',
 'their',
 'ass',
 'let',
 'turn',
 'the',
 'tables',
 'they',
 'conspired',
 'that',
 'if',
 'cops',
 'started',
 'losing',
 'people',
 'then',
 'there',
 'will',
 'be',
 'state',
 'of',
 'emergency',
 'he',
 'speculated',
 'that',
 'one',
 'of',
 'two',
 'things',
 'would',
 'happen',
 'bigass',
 'war',
 'or',
 'niers',
 'they',
 'are',
 'going',
 'to',
 'start',
 'backin',
 'up',
 'we',
 'are',
 'already',
 'getting',
 'killed',
 'out',
 'here',
 'so',
 'what',
 'the',
 'fk',
 'we',
 'got',
 'to',
 'lose',
 'sunshine',
 'could',
 'be',
 'heard',
 'saying',
 'yep',
 'that',
 'true',
 'that',
 'so',
 'fking',
 'true',
 'he',
 'said',
 'we',
 'need',
 'to',
 'turn',
 'the',
 'tables',
 'on',
 'them',
 'our',
 'kids',
 'are',
 'getting',
 'shot',
 'out',
 'here',
 'somebody',
 'needs',
 'to',
 'become',
 'sacrifice',
 'on',
 'their',
 'sidehe',
 'said',
 'everybody',
 'ain',
 'down',
 'for',
 'that',
 'st',
 'or',
 'whatever',
 'but',
 'like',
 'say',
 'everybody',
 'has',
 'different',
 'position',
 'of',
 'war',
 'he',
 'continued',
 'because',
 'they',
 'don',
 'give',
 'fk',
 'anyway',
 'he',
 'said',
 'again',
 'we',
 'might',
 'as',
 'well',
 'utilized',
 'them',
 'for',
 'that',
 'st',
 'and',
 'turn',
 'the',
 'tables',
 'on',
 'these',
 'ners',
 'he',
 'said',
 'that',
 'way',
 'we',
 'can',
 'start',
 'lookin',
 'like',
 'we',
 'ain',
 'havin',
 'that',
 'many',
 'casualties',
 'and',
 'there',
 'can',
 'be',
 'more',
 'causalities',
 'on',
 'their',
 'side',
 'instead',
 'of',
 'ours',
 'they',
 'are',
 'out',
 'their',
 'killing',
 'black',
 'people',
 'black',
 'lives',
 'don',
 'matter',
 'that',
 'what',
 'those',
 'mother',
 'fkers',
 'so',
 'we',
 'got',
 'to',
 'make',
 'it',
 'matter',
 'to',
 'them',
 'find',
 'mother',
 'fker',
 'that',
 'is',
 'alone',
 'snap',
 'his',
 'ass',
 'and',
 'then',
 'fin',
 'hang',
 'him',
 'from',
 'damn',
 'tree',
 'take',
 'picture',
 'of',
 'it',
 'and',
 'then',
 'send',
 'it',
 'to',
 'the',
 'mother',
 'fkers',
 'we',
 'just',
 'need',
 'one',
 'example',
 'and',
 'then',
 'people',
 'will',
 'start',
 'watchin',
 'this',
 'will',
 'turn',
 'the',
 'tables',
 'on',
 'st',
 'he',
 'said',
 'he',
 'said',
 'this',
 'will',
 'start',
 'trickledown',
 'effect',
 'he',
 'said',
 'that',
 'when',
 'one',
 'white',
 'person',
 'is',
 'hung',
 'and',
 'then',
 'they',
 'are',
 'just',
 'flathanging',
 'that',
 'will',
 'start',
 'the',
 'trickledown',
 'effect',
 'he',
 'continued',
 'black',
 'people',
 'are',
 'good',
 'at',
 'starting',
 'trends',
 'he',
 'said',
 'that',
 'was',
 'how',
 'to',
 'get',
 'the',
 'upperhand',
 'another',
 'black',
 'man',
 'spoke',
 'up',
 'saying',
 'they',
 'needed',
 'to',
 'kill',
 'cops',
 'that',
 'are',
 'killing',
 'us',
 'the',
 'first',
 'black',
 'male',
 'said',
 'that',
 'will',
 'be',
 'the',
 'best',
 'method',
 'right',
 'there',
 'breitbart',
 'texas',
 'previously',
 'reported',
 'how',
 'sunshine',
 'was',
 'upset',
 'when',
 'racist',
 'white',
 'people',
 'infiltrated',
 'and',
 'disrupted',
 'one',
 'of',
 'her',
 'conference',
 'calls',
 'she',
 'subsequently',
 'released',
 'the',
 'phone',
 'number',
 'of',
 'one',
 'of',
 'the',
 'infiltrators',
 'the',
 'veteran',
 'immediately',
 'started',
 'receiving',
 'threatening',
 'callsone',
 'of',
 'theyoflag',
 'movement',
 'supporters',
 'allegedly',
 'told',
 'veteran',
 'who',
 'infiltrated',
 'their',
 'publicly',
 'posted',
 'conference',
 'call',
 'we',
 'are',
 'going',
 'to',
 'rape',
 'and',
 'gut',
 'your',
 'pregnant',
 'wife',
 'and',
 'your',
 'fing',
 'piece',
 'of',
 'sht',
 'unborn',
 'creature',
 'will',
 'be',
 'hung',
 'from',
 'tree',
 'breitbart',
 'texas',
 'previously',
 'encountered',
 'sunshine',
 'at',
 'sandra',
 'bland',
 'protest',
 'at',
 'the',
 'waller',
 'county',
 'jail',
 'in',
 'texas',
 'where',
 'she',
 'said',
 'all',
 'white',
 'people',
 'should',
 'be',
 'killed',
 'she',
 'told',
 'journalists',
 'and',
 'photographers',
 'you',
 'see',
 'this',
 'nappyass',
 'hair',
 'on',
 'my',
 'head',
 'that',
 'means',
 'am',
 'one',
 'of',
 'those',
 'more',
 'militant',
 'negroes',
 'she',
 'said',
 'she',
 'was',
 'at',
 'the',
 'protest',
 'because',
 'these',
 'redneck',
 'motherfkers',
 'murdered',
 'sandra',
 'bland',
 'because',
 'she',
 'had',
 'nappy',
 'hair',
 'like',
 'me',
 'black',
 'radicals',
 'say',
 'they',
 'will',
 'be',
 'holding',
 'the',
 'imperial',
 'powers',
 'that',
 'are',
 'actually',
 'responsible',
 'for',
 'the',
 'terrorist',
 'attacks',
 'on',
 'september',
 'th',
 'accountable',
 'on',
 'that',
 'day',
 'as',
 'reported',
 'by',
 'breitbart',
 'texas',
 'there',
 'are',
 'several',
 'websites',
 'and',
 'twitter',
 'handles',
 'for',
 'the',
 'movement',
 'palmetto',
 'star',
 'describes',
 'himself',
 'as',
 'one',
 'of',
 'the',
 'head',
 'organizers',
 'he',
 'said',
 'in',
 'youtube',
 'video',
 'that',
 'supporters',
 'will',
 'be',
 'burning',
 'their',
 'symbols',
 'of',
 'the',
 'illusion',
 'of',
 'their',
 'superiority',
 'their',
 'false',
 'white',
 'supremacy',
 'like',
 'the',
 'american',
 'flag',
 'the',
 'british',
 'flag',
 'police',
 'uniforms',
 'and',
 'ku',
 'klux',
 'klan',
 'hoodssierra',
 'mcgrone',
 'or',
 'nocturnus',
 'libertus',
 'posted',
 'you',
 'too',
 'can',
 'help',
 'young',
 'afrikan',
 'clean',
 'their',
 'with',
 'the',
 'rag',
 'of',
 'oppression',
 'she',
 'posted',
 'two',
 'photos',
 'one',
 'that',
 'appears',
 'to',
 'be',
 'herself',
 'and',
 'photo',
 'of',
 'black',
 'man',
 'wiping',
 'their',
 'naked',
 'butts',
 'with',
 'the',
 'american',
 'flagfor',
 'entire',
 'story',
 'breitbart',
 'news']

In [34]:
len(sample_words)

833

In [35]:
found_sw = [i for i in sample_words if i in stop_words ]
found_sw

['on',
 'against',
 'and',
 'on',
 'by',
 'and',
 'no',
 'is',
 'from',
 'of',
 'the',
 'or',
 'and',
 'for',
 'the',
 'and',
 'of',
 'and',
 'they',
 'on',
 'to',
 'the',
 'and',
 'and',
 'to',
 'about',
 'the',
 'of',
 'in',
 'of',
 'the',
 'is',
 'she',
 'has',
 'from',
 'of',
 'her',
 'at',
 'that',
 'she',
 'was',
 'to',
 'now',
 'we',
 'to',
 'the',
 'of',
 'below',
 'is',
 'at',
 'the',
 'for',
 'and',
 'of',
 'from',
 'the',
 'can',
 'be',
 'here',
 'it',
 'was',
 'to',
 'by',
 'who',
 'to',
 'be',
 'to',
 'as',
 'he',
 'has',
 'as',
 'of',
 'when',
 'those',
 'are',
 'by',
 'themselves',
 'that',
 'when',
 'when',
 'we',
 'should',
 'them',
 'up',
 'they',
 'do',
 'when',
 'of',
 'them',
 'of',
 'out',
 'that',
 'how',
 'we',
 'should',
 'up',
 'he',
 'we',
 'up',
 'in',
 'there',
 'should',
 'be',
 'or',
 'that',
 'and',
 'then',
 'their',
 'the',
 'they',
 'that',
 'if',
 'then',
 'there',
 'will',
 'be',
 'of',
 'he',
 'that',
 'of',
 'or',
 'they',
 'are',
 'to',
 'up',
 'we',
 'are',
 'out',
 'here',
 'so',
 'what',
 'the',
 'we',
 'to',
 'be',
 'that',
 'that',
 'so',
 'he',
 'we',
 'to',
 'the',
 'on',
 'them',
 'our',
 'are',
 'out',
 'here',
 'to',
 'on',
 'their',
 'ain',
 'down',
 'for',
 'that',
 'or',
 'but',
 'has',
 'of',
 'he',
 'because',
 'they',
 'don',
 'he',
 'again',
 'we',
 'as',
 'them',
 'for',
 'that',
 'and',
 'the',
 'on',
 'these',
 'he',
 'that',
 'we',
 'can',
 'we',
 'ain',
 'that',
 'and',
 'there',
 'can',
 'be',
 'more',
 'on',
 'their',
 'of',
 'ours',
 'they',
 'are',
 'out',
 'their',
 'don',
 'that',
 'what',
 'those',
 'so',
 'we',
 'to',
 'it',
 'to',
 'them',
 'that',
 'is',
 'his',
 'and',
 'then',
 'him',
 'from',
 'of',
 'it',
 'and',
 'then',
 'it',
 'to',
 'the',
 'we',
 'just',
 'and',
 'then',
 'will',
 'this',
 'will',
 'the',
 'on',
 'he',
 'he',
 'this',
 'will',
 'he',
 'that',
 'when',
 'is',
 'and',
 'then',
 'they',
 'are',
 'just',
 'that',
 'will',
 'the',
 'he',
 'are',
 'at',
 'he',
 'that',
 'was',
 'how',
 'to',
 'the',
 'up',
 'they',
 'to',
 'that',
 'are',
 'the',
 'that',
 'will',
 'be',
 'the',
 'there',
 'how',
 'was',
 'when',
 'and',
 'of',
 'her',
 'she',
 'the',
 'of',
 'of',
 'the',
 'the',
 'of',
 'who',
 'their',
 'we',
 'are',
 'to',
 'and',
 'your',
 'and',
 'your',
 'of',
 'will',
 'be',
 'from',
 'at',
 'at',
 'the',
 'in',
 'where',
 'she',
 'all',
 'should',
 'be',
 'she',
 'and',
 'you',
 'this',
 'on',
 'my',
 'that',
 'am',
 'of',
 'those',
 'more',
 'she',
 'she',
 'was',
 'at',
 'the',
 'because',
 'these',
 'because',
 'she',
 'had',
 'me',
 'they',
 'will',
 'be',
 'the',
 'that',
 'are',
 'for',
 'the',
 'on',
 'on',
 'that',
 'as',
 'by',
 'there',
 'are',
 'and',
 'for',
 'the',
 'himself',
 'as',
 'of',
 'the',
 'he',
 'in',
 'that',
 'will',
 'be',
 'their',
 'of',
 'the',
 'of',
 'their',
 'their',
 'the',
 'the',
 'and',
 'or',
 'you',
 'too',
 'can',
 'their',
 'with',
 'the',
 'of',
 'she',
 'that',
 'to',
 'be',
 'herself',
 'and',
 'of',
 'their',
 'with',
 'the']

In [36]:
len(found_sw)

374

Percentage of stop words in row 0:

In [37]:
round((len(found_sw)/len(sample_words))*100,1)

44.9

### Updating the clean() function to remove stopwords in the text as well.

In [38]:
def clean(text):
    text = text.lower()
    text = re.sub(r'http\S+ | www\S+', '', text)
    text = re.sub(r'@\w+ | #\w+', '', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = ' '.join([i for i in text.split() if i not in stop_words and len(i) > 1]) # Updated this line
    text = re.sub(r'\s+', ' ', text)
    return text

In [39]:
df['Cleaned'] = df['Content'].apply(clean)

In [40]:
df.shape

(72095, 5)

In [41]:
df['Content'].iloc[0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO] No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News'

In [42]:
df['Cleaned'].iloc[0]

'law enforcement high alert following threats cops whites terrorists comment expected barack obama members movements called lynching hanging white people cops encouraged others radio show tuesday night turn tide kill white people cops send message killing black people americaone fyoflag organizers called sunshine radio blog show hosted texas called sunshine fing opinion radio show snapshot twitter page pm shows urging supporters call tonight continue dismantle illusion white snapshot twitter radio call invite radio show aired pm eastern standard timeduring show callers clearly call lynching killing white peoplea minute clip radio show heard provided breitbart texas someone would like referred hannibal already received death threats result interrupting conference callsan unidentified black man said mother fkers start fing like us bunch niers takin one us roll said cause already roll gangs anyway six seven black mother fckers see white person lynch ass let turn tables conspired cops started losing people state emergency speculated one two things would happen bigass war niers going start backin already getting killed fk got lose sunshine could heard saying yep true fking true said need turn tables kids getting shot somebody needs become sacrifice sidehe said everybody st whatever like say everybody different position war continued give fk anyway said might well utilized st turn tables ners said way start lookin like havin many casualties causalities side instead killing black people black lives matter mother fkers got make matter find mother fker alone snap ass fin hang damn tree take picture send mother fkers need one example people start watchin turn tables st said said start trickledown effect said one white person hung flathanging start trickledown effect continued black people good starting trends said get upperhand another black man spoke saying needed kill cops killing us first black male said best method right breitbart texas previously reported sunshine upset racist white people infiltrated disrupted one conference calls subsequently released phone number one infiltrators veteran immediately started receiving threatening callsone theyoflag movement supporters allegedly told veteran infiltrated publicly posted conference call going rape gut pregnant wife fing piece sht unborn creature hung tree breitbart texas previously encountered sunshine sandra bland protest waller county jail texas said white people killed told journalists photographers see nappyass hair head means one militant negroes said protest redneck motherfkers murdered sandra bland nappy hair like black radicals say holding imperial powers actually responsible terrorist attacks september th accountable day reported breitbart texas several websites twitter handles movement palmetto star describes one head organizers said youtube video supporters burning symbols illusion superiority false white supremacy like american flag british flag police uniforms ku klux klan hoodssierra mcgrone nocturnus libertus posted help young afrikan clean rag oppression posted two photos one appears photo black man wiping naked butts american flagfor entire story breitbart news'

In [43]:
len(df['Content'].iloc[0])

5180

In [44]:
len(df['Cleaned'].iloc[0])

3178

Checking if any null values in Cleaned column created.

In [45]:
df['Cleaned'].isnull().sum()

np.int64(0)

Checking if any empty strings after cleaning.

In [46]:
(df['Cleaned'].str.strip() == '').sum()

np.int64(48)

### Average word count before and after cleaning of text, and reduction of word count on avg. basis.

In [47]:
df['original_wc'] = df['Content'].apply(lambda x: len(x.split()))
df['cleaned_wc'] = df['Cleaned'].apply(lambda x: len(x.split()))

In [48]:
a = float(f"{df['original_wc'].mean():.1f}")
a

553.0

In [49]:
b = float(f"{df['cleaned_wc'].mean():.1f}")
b

307.5

In [50]:
c = f"{((a-b)/a)*100:.1f}"
c

'44.4'

In [51]:
df = df[df['Cleaned'].str.strip() != '']

In [52]:
df.shape

(72047, 7)

In [55]:
df[['title','text','label','Content','Cleaned']].to_csv(r'..\dataset\WELFake_Cleaned.csv', index = False)